/*
 * Copyright (c) 2020 Robert Falkenberg.
 *
 * This file is part of FALCON
 * (see https://github.com/falkenber9/falcon).
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * A copy of the GNU Affero General Public License can be found in
 * the LICENSE file in the top-level directory of this distribution
 * and at http://www.gnu.org/licenses/.
 */
#pragma once

#include <string>

// Variables autogenerated and compiled by the Version.cmake script
//extern const char* GIT_TAG;
//extern const char* GIT_REV;
//extern const char* GIT_BRANCH;

//const char* falcon_git_version(void);
//const char* falcon_git_revision(void);
//const char* falcon_git_branch(void);

class Version {
private:
    // Variables autogenerated and compiled by the Version.cmake script
    // Check "CurrentVersion.cc" in binary directory
    static const std::string GIT_TAG;
    static const std::string GIT_DIRTY;
    static const std::string GIT_REV;
    static const std::string GIT_BRANCH;
public:
    static std::string gitTag();
    static std::string gitDirty();
    static std::string gitRevision();
    static std::string gitBranch();
    static std::string gitVersion();
};
